CREATE TABLE IF NOT EXISTS `interview` (
`id ` int(11) NOT NULL,
`year` int(11) NOT NULL,
`schoolClass` int(11) NOT NULL, 
`schoolName` varchar(30) NOT NULL,
`choolDepart` varchar(30) NOT NULL,
`schoolResult` varchar(5) NULL,
`studentClass` int(11) NOT NULL,
`studentName` varchar(10) NOT NULL,
`studentPhone` varchar(10) NOT NULL,
`studentEmail` varchar(30) NOT NULL,
`studentGradeChinese` int(11) NOT NULL,
`sutdentGradeEnglish` int(11) NOT NULL,
`studentGradeMath` int(11) NOT NULL,
`studentGradeSocial` int(11) NOT NULL,
`studentGradeScience` int(11) NOT NULL,
`studentGradeTotal` int(11) NOT NULL,
`interviewMethod` text NOT NULL,
`interviewApplying` text NOT NULL,
`interviewDetail` text NOT NULL,
`interviewPaperTest` text NOT NULL,
`interviewOpinion` text NOT NULL,
`createTime` datetime  NOT NULL,
`createUser` varchar(15) NOT NULL,
`lastEditTime` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
`lastEditUser` varchar(15)  NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;